version: "2"
services:
  app:
    build: .
    environment:
      NODE_ENV: test
    command: npm test
    ports:
    - '5000:5000'
    tty: true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.17